set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[3]}]
set_property MARK_DEBUG true [get_nets design_1_i/mips_processor_0/reset]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/read_data_3[25]}]


set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[7]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[8]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mips_processor_0/U0/register_data_1_de[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/ip_fd[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_address_em[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_address_em[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_address_em[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_address_em[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_address_em[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mips_processor_0/U0/reg_write_data[10]}]
set_property MARK_DEBUG true [get_nets design_1_i/mips_processor_0/U0/reg_write_enable_em]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/mips_processor_0/reset]]

set_property MARK_DEBUG true [get_nets design_1_i/mips_processor_0/resetn]

connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/mips_processor_0/U0/reg_write_address_em[0]} {design_1_i/mips_processor_0/U0/reg_write_address_em[1]} {design_1_i/mips_processor_0/U0/reg_write_address_em[2]} {design_1_i/mips_processor_0/U0/reg_write_address_em[3]} {design_1_i/mips_processor_0/U0/reg_write_address_em[4]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/mips_processor_0/U0/reg_write_data[0]} {design_1_i/mips_processor_0/U0/reg_write_data[1]} {design_1_i/mips_processor_0/U0/reg_write_data[2]} {design_1_i/mips_processor_0/U0/reg_write_data[3]} {design_1_i/mips_processor_0/U0/reg_write_data[4]} {design_1_i/mips_processor_0/U0/reg_write_data[5]} {design_1_i/mips_processor_0/U0/reg_write_data[6]} {design_1_i/mips_processor_0/U0/reg_write_data[7]} {design_1_i/mips_processor_0/U0/reg_write_data[8]} {design_1_i/mips_processor_0/U0/reg_write_data[9]} {design_1_i/mips_processor_0/U0/reg_write_data[10]} {design_1_i/mips_processor_0/U0/reg_write_data[11]} {design_1_i/mips_processor_0/U0/reg_write_data[12]} {design_1_i/mips_processor_0/U0/reg_write_data[13]} {design_1_i/mips_processor_0/U0/reg_write_data[14]} {design_1_i/mips_processor_0/U0/reg_write_data[15]} {design_1_i/mips_processor_0/U0/reg_write_data[16]} {design_1_i/mips_processor_0/U0/reg_write_data[17]} {design_1_i/mips_processor_0/U0/reg_write_data[18]} {design_1_i/mips_processor_0/U0/reg_write_data[19]} {design_1_i/mips_processor_0/U0/reg_write_data[20]} {design_1_i/mips_processor_0/U0/reg_write_data[21]} {design_1_i/mips_processor_0/U0/reg_write_data[22]} {design_1_i/mips_processor_0/U0/reg_write_data[23]} {design_1_i/mips_processor_0/U0/reg_write_data[24]} {design_1_i/mips_processor_0/U0/reg_write_data[25]} {design_1_i/mips_processor_0/U0/reg_write_data[26]} {design_1_i/mips_processor_0/U0/reg_write_data[27]} {design_1_i/mips_processor_0/U0/reg_write_data[28]} {design_1_i/mips_processor_0/U0/reg_write_data[29]} {design_1_i/mips_processor_0/U0/reg_write_data[30]} {design_1_i/mips_processor_0/U0/reg_write_data[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/mips_processor_0/U0/ip_fd[0]} {design_1_i/mips_processor_0/U0/ip_fd[1]} {design_1_i/mips_processor_0/U0/ip_fd[2]} {design_1_i/mips_processor_0/U0/ip_fd[3]} {design_1_i/mips_processor_0/U0/ip_fd[4]} {design_1_i/mips_processor_0/U0/ip_fd[5]} {design_1_i/mips_processor_0/U0/ip_fd[6]} {design_1_i/mips_processor_0/U0/ip_fd[7]} {design_1_i/mips_processor_0/U0/ip_fd[8]} {design_1_i/mips_processor_0/U0/ip_fd[9]} {design_1_i/mips_processor_0/U0/ip_fd[10]} {design_1_i/mips_processor_0/U0/ip_fd[11]} {design_1_i/mips_processor_0/U0/ip_fd[12]} {design_1_i/mips_processor_0/U0/ip_fd[13]} {design_1_i/mips_processor_0/U0/ip_fd[14]} {design_1_i/mips_processor_0/U0/ip_fd[15]} {design_1_i/mips_processor_0/U0/ip_fd[16]} {design_1_i/mips_processor_0/U0/ip_fd[17]} {design_1_i/mips_processor_0/U0/ip_fd[18]} {design_1_i/mips_processor_0/U0/ip_fd[19]} {design_1_i/mips_processor_0/U0/ip_fd[20]} {design_1_i/mips_processor_0/U0/ip_fd[21]} {design_1_i/mips_processor_0/U0/ip_fd[22]} {design_1_i/mips_processor_0/U0/ip_fd[23]} {design_1_i/mips_processor_0/U0/ip_fd[24]} {design_1_i/mips_processor_0/U0/ip_fd[25]} {design_1_i/mips_processor_0/U0/ip_fd[26]} {design_1_i/mips_processor_0/U0/ip_fd[27]} {design_1_i/mips_processor_0/U0/ip_fd[28]} {design_1_i/mips_processor_0/U0/ip_fd[29]} {design_1_i/mips_processor_0/U0/ip_fd[30]} {design_1_i/mips_processor_0/U0/ip_fd[31]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/mips_processor_0/read_data_3[0]} {design_1_i/mips_processor_0/read_data_3[1]} {design_1_i/mips_processor_0/read_data_3[2]} {design_1_i/mips_processor_0/read_data_3[3]} {design_1_i/mips_processor_0/read_data_3[4]} {design_1_i/mips_processor_0/read_data_3[5]} {design_1_i/mips_processor_0/read_data_3[6]} {design_1_i/mips_processor_0/read_data_3[7]} {design_1_i/mips_processor_0/read_data_3[8]} {design_1_i/mips_processor_0/read_data_3[9]} {design_1_i/mips_processor_0/read_data_3[10]} {design_1_i/mips_processor_0/read_data_3[11]} {design_1_i/mips_processor_0/read_data_3[12]} {design_1_i/mips_processor_0/read_data_3[13]} {design_1_i/mips_processor_0/read_data_3[14]} {design_1_i/mips_processor_0/read_data_3[15]} {design_1_i/mips_processor_0/read_data_3[16]} {design_1_i/mips_processor_0/read_data_3[17]} {design_1_i/mips_processor_0/read_data_3[18]} {design_1_i/mips_processor_0/read_data_3[19]} {design_1_i/mips_processor_0/read_data_3[20]} {design_1_i/mips_processor_0/read_data_3[21]} {design_1_i/mips_processor_0/read_data_3[22]} {design_1_i/mips_processor_0/read_data_3[23]} {design_1_i/mips_processor_0/read_data_3[24]} {design_1_i/mips_processor_0/read_data_3[25]} {design_1_i/mips_processor_0/read_data_3[26]} {design_1_i/mips_processor_0/read_data_3[27]} {design_1_i/mips_processor_0/read_data_3[28]} {design_1_i/mips_processor_0/read_data_3[29]} {design_1_i/mips_processor_0/read_data_3[30]} {design_1_i/mips_processor_0/read_data_3[31]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/mips_processor_0/U0/reg_write_enable_em]]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/mips_processor_0/resetn]]

set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/i_tdata[0]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_pipe_0/resetn]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/i_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/i_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/i_tdata[3]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_pipe_0/i_tready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_pipe_0/o_tready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_pipe_0/o_tvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axi_pipe_0/i_tvalid]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/i_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/o_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_pipe_0/U0/PROC/ip_f[30]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 5 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_pipe_0/i_tdata[0]} {design_1_i/axi_pipe_0/i_tdata[1]} {design_1_i/axi_pipe_0/i_tdata[2]} {design_1_i/axi_pipe_0/i_tdata[3]} {design_1_i/axi_pipe_0/i_tdata[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_f[0]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[1]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[2]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[3]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[4]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[5]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[6]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[7]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[8]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[9]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[10]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[11]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[12]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[13]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[14]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[15]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[16]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[17]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[18]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[19]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[20]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[21]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[22]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[23]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[24]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[25]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[26]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[27]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[28]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[29]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[30]} {design_1_i/axi_pipe_0/U0/PROC/ip_f[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_pipe_0/o_tdata[0]} {design_1_i/axi_pipe_0/o_tdata[1]} {design_1_i/axi_pipe_0/o_tdata[2]} {design_1_i/axi_pipe_0/o_tdata[3]} {design_1_i/axi_pipe_0/o_tdata[4]} {design_1_i/axi_pipe_0/o_tdata[5]} {design_1_i/axi_pipe_0/o_tdata[6]} {design_1_i/axi_pipe_0/o_tdata[7]} {design_1_i/axi_pipe_0/o_tdata[8]} {design_1_i/axi_pipe_0/o_tdata[9]} {design_1_i/axi_pipe_0/o_tdata[10]} {design_1_i/axi_pipe_0/o_tdata[11]} {design_1_i/axi_pipe_0/o_tdata[12]} {design_1_i/axi_pipe_0/o_tdata[13]} {design_1_i/axi_pipe_0/o_tdata[14]} {design_1_i/axi_pipe_0/o_tdata[15]} {design_1_i/axi_pipe_0/o_tdata[16]} {design_1_i/axi_pipe_0/o_tdata[17]} {design_1_i/axi_pipe_0/o_tdata[18]} {design_1_i/axi_pipe_0/o_tdata[19]} {design_1_i/axi_pipe_0/o_tdata[20]} {design_1_i/axi_pipe_0/o_tdata[21]} {design_1_i/axi_pipe_0/o_tdata[22]} {design_1_i/axi_pipe_0/o_tdata[23]} {design_1_i/axi_pipe_0/o_tdata[24]} {design_1_i/axi_pipe_0/o_tdata[25]} {design_1_i/axi_pipe_0/o_tdata[26]} {design_1_i/axi_pipe_0/o_tdata[27]} {design_1_i/axi_pipe_0/o_tdata[28]} {design_1_i/axi_pipe_0/o_tdata[29]} {design_1_i/axi_pipe_0/o_tdata[30]} {design_1_i/axi_pipe_0/o_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/axi_pipe_0/i_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axi_pipe_0/i_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[16]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[17]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[18]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[20]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[21]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[22]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[24]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[25]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[26]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[30]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {design_1_i/axi_pipe_0/U0/PROC/ip_fd_reg_n_0_[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list design_1_i/axi_pipe_0/o_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list design_1_i/axi_pipe_0/o_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list design_1_i/axi_pipe_0/resetn]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
